name: Génération calendrier FR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # Tous les jours à 06h00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests

      - run: mkdir -p calendar

      - run: python scripts/translate_ics.py
