name: Génération & déploiement calendrier FR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"    # 06h00 Paris
    - cron: "0 10 * * *"   # 12h00 Paris
    - cron: "0 16 * * *"   # 18h00 Paris
    - cron: "1 22 * * *"   # 00h01 Paris

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout du dépôt
      - uses: actions/checkout@v4

      # 2️⃣ Installer Python et dépendances
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 3️⃣ Créer le dossier calendar si inexistant
      - run: mkdir -p calendar

      # 4️⃣ Lancer le script Python pour générer ICS
      - run: python scripts/translate_ics.py

      # 5️⃣ Commit et push du fichier ICS
      - name: Commit et push avec GITHUB_TOKEN
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add calendar/gocal_fr.ics
          git commit -m "MàJ calendrier FR" || echo "Rien à commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/SneakyOnTv/pokemon-go-calendar-fr.git main

      # 6️⃣ Créer ou mettre à jour la release
      - name: Créer/MàJ release et upload ICS
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.0
          name: Calendrier FR
          allowUpdates: true
          artifact: calendar/gocal_fr.ics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 7️⃣ Notification de succès GitHub
      - name: Notification de succès dans GitHub
        if: success()
        run: echo "::notice title=Calendrier FR::✅ Auto MàJ calendrier FR réussie !"

      # 8️⃣ Notification Pushover
      - name: Notification push Pushover
        if: success()
        run: |
          curl -s \
            --form-string "token=${{ secrets.PUSHOVER_TOKEN }}" \
            --form-string "user=${{ secrets.PUSHOVER_USER }}" \
            --form-string "message=📅Calendrier PoGo FR → Auto M.A.J réussie ! ✅" \
            https://api.pushover.net/1/messages.json
