name: Génération calendrier FR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"    # 06h00 Paris
    - cron: "0 10 * * *"   # 12h00 Paris
    - cron: "0 16 * * *"   # 18h00 Paris
    - cron: "1 22 * * *"   # 00h01 Paris

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout du dépôt
      - uses: actions/checkout@v4
      # 2️⃣ Installer Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      # 3️⃣ Installer requests
      - run: pip install requests
      # 4️⃣ Créer le dossier calendar si inexistant
      - run: mkdir -p calendar
      # 5️⃣ Lancer le script Python
      - run: python scripts/translate_ics.py
      # 6️⃣ Commit et push du fichier généré
      - name: Commit et push gocal_fr.ics
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add calendar/gocal_fr.ics
          git commit -m "Mise à jour du calendrier FR"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
