name: Génération & déploiement calendrier FR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"    # 06h00 Paris
    - cron: "0 10 * * *"   # 12h00 Paris
    - cron: "0 16 * * *"   # 18h00 Paris
    - cron: "1 22 * * *"   # 00h01 Paris

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout du dépôt
      - uses: actions/checkout@v4

      # 2️⃣ Installer Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ Mettre en cache les dépendances Python
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4️⃣ Installer les dépendances Python depuis requirements.txt
      - name: Installer dependencies Python
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt --quiet

      # 5️⃣ Créer le dossier calendar
      - run: mkdir -p calendar

      # 6️⃣ Lancer le script de traduction
      - name: Générer le fichier ICS traduit
        run: python scripts/translate_ics.py

      # 7️⃣ Commit et push du fichier ICS
      - name: Commit et push ICS
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add calendar/gocal_fr.ics
          git commit -m "MàJ calendrier FR" || echo "Rien à commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/SneakyOnTv/pokemon-go-calendar-fr.git main

      # 8️⃣ Déployer sur GitHub Pages
      - name: Build & deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./calendar
          publish_branch: gh-pages

      # 9️⃣ Créer/MàJ release et upload ICS
      - name: Créer/MàJ release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.0
          name: Calendrier FR
          allowUpdates: true
          artifact: calendar/gocal_fr.ics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 🔟 Notifications après réussite complète
      - name: Notification GitHub & Pushover
        if: success()
        run: |
          echo "::notice title=Calendrier FR::✅ Auto MàJ calendrier FR réussie !"
          curl -s \
            --form-string "token=${{ secrets.PUSHOVER_TOKEN }}" \
            --form-string "user=${{ secrets.PUSHOVER_USER }}" \
            --form-string "message=📅Calendrier PoGo FR → Auto M.A.J réussie ! ✅" \
            https://api.pushover.net/1/messages.json
